### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by SoK05** [Mrmaxmeier/stuff#3]
Sorry for adding an issue here, but since you archived Mod Manager, I had no way to contact you.
You may know me as TheMikirog's friend, you provided us with a bob plugin few years ago. How's it going? :)

I wanted to ask you for permission to use your Quick-Game mod in my new modpack. Some other guy already updated it to 1.7, but since it's yours, I wanted to reach you. Sorry again for writing here, I really don't know another way to get in touch.

Cheers!

**Comment by Mrmaxmeier** [comment]
Hi,

feel free to re-use my BombSquad mods. You can also add the updated version to the new plugin repository if you want :)

_EDIT_: Looks like some version of the Quick-Game mod already found it's way into the new repo. ^^

Cheers!
